import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggleButton } from "@/components/theme-toggle-button"; // Import ThemeToggleButton
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>{/* Ensure no space before body */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-screen">
            {/* Sidebar */}
            <aside className="w-64 bg-zinc-100 dark:bg-zinc-800 p-4 border-r border-zinc-200 dark:border-zinc-700 flex flex-col"> {/* Added flex flex-col */}
            <h2 className="text-xl font-bold mb-6 text-zinc-900 dark:text-zinc-100">Flow-API</h2>
            <nav className="space-y-2">
              <Link href="/dashboard" className="flex items-center px-3 py-2 text-zinc-700 dark:text-zinc-300 hover:bg-zinc-200 dark:hover:bg-zinc-700 rounded-md transition-colors">
                {/* Placeholder for an icon */}
                <span className="mr-2">📊</span> Dashboard
              </Link>
              <Link href="/services" className="flex items-center px-3 py-2 text-zinc-700 dark:text-zinc-300 hover:bg-zinc-200 dark:hover:bg-zinc-700 rounded-md transition-colors">
                {/* Placeholder for an icon */}
                <span className="mr-2">🔌</span> Services
              </Link>
                {/* Add more links as needed */}
              </nav>
              <div className="mt-auto p-4"> {/* Push toggle to bottom and add padding */}
                <ThemeToggleButton />
              </div>
            </aside>

            {/* Main Content */}
            <main className="flex-grow p-6 bg-background text-foreground"> {/* Use theme variables */}
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
